# PIPELINE DEFINITION
# Name: fraud-detection-e2e-pipeline
components:
  comp-importer:
    executorLabel: exec-importer
    inputDefinitions:
      parameters:
        uri:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        artifact:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-read-dataset:
    executorLabel: exec-read-dataset
    inputDefinitions:
      artifacts:
        dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-importer:
      importer:
        artifactUri:
          constant: minio://mlpipeline/artifacts/input/raw_transaction_datasource.csv
        reimport: true
        typeSchema:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    exec-read-dataset:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - read_dataset
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.11.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef read_dataset(dataset: Input[Dataset]):\n    with open(dataset.path,\
          \ \"r\") as f:\n        data = f.read()\n    print(\"Dataset content:\"\
          , data)\n\n"
        image: python:3.10
pipelineInfo:
  name: fraud-detection-e2e-pipeline
root:
  dag:
    tasks:
      importer:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-importer
        inputs:
          parameters:
            uri:
              runtimeValue:
                constant: minio://mlpipeline/artifacts/input/raw_transaction_datasource.csv
        taskInfo:
          name: importer
      read-dataset:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-read-dataset
        dependentTasks:
        - importer
        inputs:
          artifacts:
            dataset:
              taskOutputArtifact:
                outputArtifactKey: artifact
                producerTask: importer
        taskInfo:
          name: read-dataset
schemaVersion: 2.1.0
sdkVersion: kfp-2.11.0
